# Generated by Django 3.2.25 on 2025-03-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='achieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='achieved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
