# Generated by Django 3.2.25 on 2025-03-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20250324_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='template_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
