# Generated by Django 3.2.25 on 2025-03-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_template_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitrecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='habitrecord',
            unique_together=set(),
        ),
    ]
