# Generated by Django 3.2.25 on 2025-03-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
