# Generated by Django 3.2.25 on 2025-04-02 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0007_habitbadge'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('silver_badge', 'Silver'), ('gold_badge', 'Gold'), ('platinum_badge', 'Platinum'), ('streak_10_badge', '10-Day Streak'), ('completed_preset_badge', 'Completed Preset')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'habit', 'badge_type')},
            },
        ),
        migrations.DeleteModel(
            name='HabitBadge',
        ),
    ]
