# Generated by Django 3.2.25 on 2025-03-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20250322_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecurityanswer',
            name='question_text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
