# Generated by Django 3.2.25 on 2025-04-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_loginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='LoginActivity',
        ),
    ]
