# Generated by Django 3.2.25 on 2025-04-02 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20250402_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('login_streak', 'Login Streak'), ('consistency', 'Consistency'), ('first_win', 'First Win'), ('triple_habit', 'Triple Habit')], max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('achieved_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
