# Generated by Django 3.2.25 on 2025-04-02 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userbadge'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('login_streak_badge', 'Login Streak'), ('consistency_badge', 'Consistency'), ('first_win_badge', 'First Win'), ('triple_habit_badge', 'Triple Habit')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge_type')},
            },
        ),
        migrations.DeleteModel(
            name='UserBadge',
        ),
    ]
